server:
  port: 7005
  forward-headers-strategy: framework
spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
springdoc:
  swagger-ui:
    urls:
      - name: auth
        url: /sauauth/v3/api-docs
      - name: sau
        url: /saurestboot/v3/api-docs
      - name: asker
        url: /sauasker/v3/api-docs
  api-docs:
    groups:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7003/eureka